const Refs = {
     bodyRef: document.querySelector('body'),
     aboutRef: document.querySelector('.about'),
     bgImg: document.querySelector('.bg-image'),
     headerListItemsRef: document.querySelectorAll('.header__list-item'),
     headerAfterRef: document.querySelectorAll('.header__list-container'),
     headerListLinkRef: document.querySelectorAll('.header__list-link'),
     list : document.querySelector('.main__list'),
     links : document.querySelectorAll('.main__list-item'),
     innerContainer : document.querySelector('.main__inner-container'),
     innerItems : document.querySelectorAll('.main__inner-item'),
     innerList : document.querySelector('.main__inner-list'),
     innerImgLink : document.querySelectorAll('.main__inner-img-link'),
     innerImg : document.querySelectorAll('.main__inner-img'),
     innerTitle : document.querySelector('.main__inner-title'),
     innerBtn : document.querySelector('.main__inner-btn'),
     overlayRef: document.querySelector('.Overlay'),
     modalRef: document.querySelector('.Modal'),
     modalImgRef : document.querySelector('.modal__img'),
     btnNext : document.querySelector('.modal__btn--next'),
     btnPrev: document.querySelector('.modal__btn--prev'),
     swipeTopRef: document.querySelector('.gallery-top'),
     svipeBottomRef: document.querySelector('.gallery-thumbs'),
}
export default Refs;